// flow-typed signature: e09a7fe686909ac1dc492d4498088e32
// flow-typed version: <<STUB>>/nullthrows_v1.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nullthrows'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nullthrows' {
  declare module.exports: <T>(t: ?T) => T;
}
